- name: bug
  color: "d73a4a"
  description: Something isn't working

- name: feature
  color: "0e8a16"
  description: New feature or enhancement

- name: documentation
  color: "0075ca"
  description: Improvements or additions to documentation

- name: help wanted
  color: "008672"
  description: Extra attention is needed

- name: good first issue
  color: "7057ff"
  description: Good for newcomers

- name: question
  color: "d876e3"
  description: Further information is requested

- name: wontfix
  color: "ffffff"
  description: This will not be worked on

- name: invalid
  color: "e4e669"
  description: This doesn't seem right

- name: chore
  color: "f9d0c4"
  description: Maintenance, refactors or tooling

- name: performance
  color: "fbca04"
  description: Improve speed or responsiveness

- name: test
  color: "1d76db"
  description: Related to testing or test coverage
