Controllers:
  resource:
    path: ../src/Controller/
    namespace: ItechWorld\UserManagementBundle\Controller
  type: attribute

api_login:
  path: /api/login

when@dev:
  api_doc:
    path: /docs
    controller: api_platform.action.documentation
